---
assertion_consumer_service_url: https://localhost:4567/consume
issuer: USA-IDV
idp_sso_target_url: https://upaya-dev.ngrok.io/api/saml/auth
idp_cert_fingerprint: F9:A3:9B:2F:8F:1C:E2:79:27:69:EB:32:ED:2A:D5:A2:A7:58:5F:C0:74:8A:4A:03:D9:0F:77:A5:89:7F:F9:68
name_identifier_format: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
security:
  authn_requests_signed: true
